/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateFLIPAddress"
      | "createFLIP"
      | "feeVault"
      | "registry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FLIPCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateFLIPAddress",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createFLIP",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "feeVault", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "calculateFLIPAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createFLIP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
}

export namespace FLIPCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    flipAddress: AddressLike,
    name: string,
    symbol: string,
    initialPrice: BigNumberish,
    maxSupply: BigNumberish,
    creatorFeePercent: BigNumberish,
    baseURI: string
  ];
  export type OutputTuple = [
    creator: string,
    flipAddress: string,
    name: string,
    symbol: string,
    initialPrice: bigint,
    maxSupply: bigint,
    creatorFeePercent: bigint,
    baseURI: string
  ];
  export interface OutputObject {
    creator: string;
    flipAddress: string;
    name: string;
    symbol: string;
    initialPrice: bigint;
    maxSupply: bigint;
    creatorFeePercent: bigint;
    baseURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Factory extends BaseContract {
  connect(runner?: ContractRunner | null): Factory;
  waitForDeployment(): Promise<this>;

  interface: FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateFLIPAddress: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _initialPrice: BigNumberish,
      _maxSupply: BigNumberish,
      _creatorFeePercent: BigNumberish,
      _baseURI: string
    ],
    [string],
    "view"
  >;

  createFLIP: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _initialPrice: BigNumberish,
      _maxSupply: BigNumberish,
      _creatorFeePercent: BigNumberish,
      _baseURI: string
    ],
    [string],
    "nonpayable"
  >;

  feeVault: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateFLIPAddress"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _initialPrice: BigNumberish,
      _maxSupply: BigNumberish,
      _creatorFeePercent: BigNumberish,
      _baseURI: string
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createFLIP"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _initialPrice: BigNumberish,
      _maxSupply: BigNumberish,
      _creatorFeePercent: BigNumberish,
      _baseURI: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FLIPCreated"
  ): TypedContractEvent<
    FLIPCreatedEvent.InputTuple,
    FLIPCreatedEvent.OutputTuple,
    FLIPCreatedEvent.OutputObject
  >;

  filters: {
    "FLIPCreated(address,address,string,string,uint256,uint256,uint256,string)": TypedContractEvent<
      FLIPCreatedEvent.InputTuple,
      FLIPCreatedEvent.OutputTuple,
      FLIPCreatedEvent.OutputObject
    >;
    FLIPCreated: TypedContractEvent<
      FLIPCreatedEvent.InputTuple,
      FLIPCreatedEvent.OutputTuple,
      FLIPCreatedEvent.OutputObject
    >;
  };
}
