/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBaseNFT__factory } from "./IBaseNFT__factory";
export { IPrice__factory } from "./IPrice__factory";
export { IStorage__factory } from "./IStorage__factory";
export { ITrade__factory } from "./ITrade__factory";
