/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBaseNFT } from "./IBaseNFT";
export type { IPrice } from "./IPrice";
export type { IStorage } from "./IStorage";
export type { ITrade } from "./ITrade";
