/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllAvailableTokens"
      | "getAvailableTokenByIndex"
      | "getAvailableTokensCount"
      | "getAvailableTokensPaginated"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllAvailableTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableTokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableTokensCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableTokensPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllAvailableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableTokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableTokensCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableTokensPaginated",
    data: BytesLike
  ): Result;
}

export interface IStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IStorage;
  waitForDeployment(): Promise<this>;

  interface: IStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllAvailableTokens: TypedContractMethod<[], [bigint[]], "view">;

  getAvailableTokenByIndex: TypedContractMethod<
    [index: BigNumberish],
    [bigint],
    "view"
  >;

  getAvailableTokensCount: TypedContractMethod<[], [bigint], "view">;

  getAvailableTokensPaginated: TypedContractMethod<
    [start: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllAvailableTokens"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getAvailableTokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableTokensCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableTokensPaginated"
  ): TypedContractMethod<
    [start: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  filters: {};
}
